const exercises = [
  {
    id: 1,
    name: "Push-Up",
    category: "chest",
    muscles: ["Chest", "Triceps", "Shoulders"],
    difficulty: "beginner",
    sets: "3–4",
    reps: "10–20",
    description:
      "Start in a high plank with hands shoulder-width apart. Lower your chest to just above the floor while keeping your core tight and elbows at roughly 45°, then press back up to full arm extension. Keep your body in a straight line throughout.",
    videoId: "IODxDxX7oi4",
  },
  {
    id: 2,
    name: "Squat",
    category: "legs",
    muscles: ["Quadriceps", "Glutes", "Hamstrings"],
    difficulty: "beginner",
    sets: "3–4",
    reps: "8–15",
    description:
      "Stand with feet shoulder-width apart, toes slightly turned out. Push your hips back and bend your knees, descending until your thighs are at least parallel to the floor. Drive through your heels to stand back up, squeezing your glutes at the top.",
    videoId: "aclHkVaku9U",
  },
  {
    id: 3,
    name: "Pull-Up",
    category: "back",
    muscles: ["Lats", "Biceps", "Rear Delts"],
    difficulty: "intermediate",
    sets: "3",
    reps: "5–10",
    description:
      "Hang from a bar with a pronated (overhand) grip slightly wider than shoulder-width. Retract your shoulder blades, then pull your chin above the bar by driving your elbows down and back. Lower under control to a full hang before the next rep.",
    videoId: "eGo4IYlbE5g",
  },
  {
    id: 4,
    name: "Deadlift",
    category: "back",
    muscles: ["Hamstrings", "Glutes", "Lower Back", "Traps"],
    difficulty: "intermediate",
    sets: "3–5",
    reps: "3–8",
    description:
      "Stand with the barbell over mid-foot, grip just outside your legs. Hinge at the hips, flatten your back, and take a deep breath. Push the floor away to lift the bar, keeping it close to your body, then lock out hips and knees at the top. Hinge back down under control.",
    videoId: "op9kVnSso6Q",
  },
  {
    id: 5,
    name: "Bench Press",
    category: "chest",
    muscles: ["Chest", "Triceps", "Front Delts"],
    difficulty: "intermediate",
    sets: "3–4",
    reps: "6–12",
    description:
      "Lie on a flat bench, feet flat on the floor. Unrack the bar with arms fully extended over your chest. Lower it with control until it lightly touches your lower chest, then press back up explosively. Keep your shoulder blades pinched back and maintain a slight natural arch.",
    videoId: "vcBig73ojpE",
  },
  {
    id: 6,
    name: "Plank",
    category: "core",
    muscles: ["Core", "Shoulders", "Glutes"],
    difficulty: "beginner",
    sets: "3",
    reps: "30–60 s",
    description:
      "Place your forearms on the floor, elbows under your shoulders. Lift your hips so your body forms a straight line from head to heels. Brace your core as if you're about to take a punch, squeeze your glutes, and breathe normally. Hold without letting your hips sag or pike.",
    videoId: "pvIjsG5Svck",
  },
  {
    id: 7,
    name: "Burpee",
    category: "cardio",
    muscles: ["Full Body"],
    difficulty: "intermediate",
    sets: "3–4",
    reps: "10–15",
    description:
      "From standing, drop your hands to the floor and jump your feet back to a plank. Perform a push-up, jump your feet back to your hands, then explode upward into a jump, reaching your arms overhead. Land softly and go straight into the next rep.",
    videoId: "TU8QYVW0gDU",
  },
  {
    id: 8,
    name: "Lunge",
    category: "legs",
    muscles: ["Quadriceps", "Glutes", "Hamstrings"],
    difficulty: "beginner",
    sets: "3",
    reps: "10–12 each leg",
    description:
      "Stand tall, then step one foot forward and lower your back knee toward the floor until both knees are at ~90°. Keep your torso upright and your front knee over your ankle. Push through your front heel to return to standing, then repeat on the other side.",
    videoId: "QOVaHwm-Q6U",
  },
  {
    id: 9,
    name: "Dip",
    category: "chest",
    muscles: ["Triceps", "Chest", "Front Delts"],
    difficulty: "intermediate",
    sets: "3",
    reps: "8–12",
    description:
      "Support yourself on parallel bars with arms fully extended. Lean slightly forward (for chest focus) or stay upright (for triceps focus). Lower yourself by bending the elbows until your upper arms are parallel to the floor, then press back up to full lockout.",
    videoId: "2z8JmcrW-As",
  },
  {
    id: 10,
    name: "Mountain Climber",
    category: "cardio",
    muscles: ["Core", "Hip Flexors", "Shoulders"],
    difficulty: "beginner",
    sets: "3",
    reps: "20–30 each leg",
    description:
      "Start in a high plank position with your core tight and hips level. Drive one knee toward your chest, then quickly switch legs in a running motion. Keep your hips down throughout and breathe rhythmically.",
    videoId: "nmwgirgXLYM",
  },
  {
    id: 11,
    name: "Overhead Press",
    category: "shoulders",
    muscles: ["Shoulders", "Triceps", "Upper Traps"],
    difficulty: "intermediate",
    sets: "3–4",
    reps: "6–10",
    description:
      "Stand with a barbell or dumbbells at shoulder height, elbows just in front of the bar. Brace your core and glutes, then press the weight directly overhead until your arms are fully locked out. Lower under control back to the start position.",
    videoId: "2yjwXTZQDDI",
  },
  {
    id: 12,
    name: "Romanian Deadlift",
    category: "legs",
    muscles: ["Hamstrings", "Glutes", "Lower Back"],
    difficulty: "intermediate",
    sets: "3–4",
    reps: "8–12",
    description:
      "Hold a barbell or dumbbells in front of your thighs. Hinge at the hips, pushing them back while keeping a slight knee bend and a flat back. Lower the weight along your legs until you feel a deep hamstring stretch, then drive your hips forward to stand back up.",
    videoId: "jEy_czb3RKA",
  },
  {
    id: 13,
    name: "Bicep Curl",
    category: "arms",
    muscles: ["Biceps", "Forearms"],
    difficulty: "beginner",
    sets: "3",
    reps: "10–15",
    description:
      "Stand holding dumbbells with palms facing forward, elbows pinned to your sides. Curl the weights toward your shoulders by contracting your biceps, then lower them slowly back to the starting position. Avoid swinging your torso to cheat the weight up.",
    videoId: "ykJmrZ5v0Oo",
  },
  {
    id: 14,
    name: "Tricep Dip (Bench)",
    category: "arms",
    muscles: ["Triceps", "Chest"],
    difficulty: "beginner",
    sets: "3",
    reps: "10–15",
    description:
      "Sit on the edge of a bench and place your hands on either side of your hips. Slide your body off the bench and lower yourself by bending your elbows to about 90°. Press back up through your palms to full arm extension. Keep your back close to the bench throughout.",
    videoId: "0326dy_-CzM",
  },
  {
    id: 15,
    name: "Leg Raise",
    category: "core",
    muscles: ["Lower Abs", "Hip Flexors"],
    difficulty: "beginner",
    sets: "3",
    reps: "12–20",
    description:
      "Lie flat on your back with legs straight and hands under your lower back for support. Keeping your legs together and nearly straight, raise them to 90° by contracting your abs. Lower slowly back down without letting your heels touch the floor before the next rep.",
    videoId: "JB2oyawG9KI",
  },
  {
    id: 16,
    name: "Face Pull",
    category: "shoulders",
    muscles: ["Rear Delts", "Rotator Cuff", "Traps"],
    difficulty: "beginner",
    sets: "3–4",
    reps: "15–20",
    description:
      "Set a cable machine at upper-chest height and attach a rope. Grasp both ends with an overhand grip and pull the rope toward your face, externally rotating your arms so your knuckles face away. Squeeze your rear delts at full contraction, then return under control.",
    videoId: "rep-qVOkqgk",
  },
];
